/**
 * Incremental conversation reuse (gateway session store).
 *
 * OpenCode resends the whole conversation history on every request, so a
 * 147KB+ prompt (system prompt, tools, every prior turn) is re-framed and
 * re-processed by agy from scratch on each turn — the dominant cost of a
 * chat request. This store lets the gateway resume the agy conversation
 * (`--conversation <id>`) and send only the messages added since the last
 * turn instead.
 *
 * A stable fingerprint is computed over the user/assistant/tool message
 * sequence (the system message is excluded: it is regenerated by the client
 * and varies between requests). Host-injected context blocks such as
 * OpenCode's `<openviking-context>` are stripped from user messages before
 * hashing, because they change every turn even though the user's real input
 * is unchanged. Prefix matching means request N+1 (a superset of request N)
 * finds request N's entry and resumes it; LRU eviction bounds memory.
 */
import type { OpenAIMessage } from "./prompt.js";
import { stripHostContext } from "./prompt.js";

export function stableMessageText(role: string, content: string): string {
  return role === "user" ? stripHostContext(content) : content;
}

/** 64-bit djb2 rolling hash over role + content of one message. */
function messageHash(role: string, content: string): bigint {
  const text = `${role}\u0000${stableMessageText(role, content)}`;
  let hash = 5381n;
  for (let index = 0; index < text.length; index += 1) {
    hash = ((hash << 5n) + hash + BigInt(text.charCodeAt(index))) & 0xffffffffffffffffn;
  }
  return hash;
}

/** hashes[i] = fingerprint of sequence[0..i). hashes[0] = 0n. */
export function prefixHashes(sequence: readonly OpenAIMessage[]): bigint[] {
  const hashes = new Array<bigint>(sequence.length + 1);
  hashes[0] = 0n;
  for (let index = 0; index < sequence.length; index += 1) {
    const message = sequence[index];
    if (message === undefined) {
      continue;
    }
    hashes[index + 1] = (hashes[index] ?? 0n) ^ messageHash(message.role, message.content);
  }
  return hashes;
}

export interface SessionHit {
  readonly conversationId: string;
  readonly seenCount: number;
}

interface SessionEntry {
  readonly fingerprint: bigint;
  readonly count: number;
  readonly conversationId: string;
}

export class SessionStore {
  private readonly entries = new Map<string, SessionEntry>();
  private readonly capacity: number;

  constructor(capacity: number) {
    this.capacity = Math.max(0, Math.floor(capacity));
  }

  get size(): number {
    return this.entries.size;
  }

  /** Returns the conversation whose message sequence is a strict prefix of
   * `sequence`, preferring the longest match (most recent continuation).
   * System messages are excluded from the fingerprint internally. */
  lookup(sequence: readonly OpenAIMessage[]): SessionHit | null {
    if (this.capacity === 0 || this.entries.size === 0) {
      return null;
    }
    const filtered = sequence.filter((message) => message.role !== "system");
    if (filtered.length === 0) {
      return null;
    }
    const hashes = prefixHashes(filtered);
    let bestKey: string | null = null;
    let best: SessionHit | null = null;
    for (const [key, entry] of this.entries) {
      if (entry.count <= filtered.length && entry.count >= (best?.seenCount ?? 0)) {
        const prefix = hashes[entry.count];
        if (prefix !== undefined && prefix === entry.fingerprint) {
          bestKey = key;
          best = { conversationId: entry.conversationId, seenCount: entry.count };
        }
      }
    }
    if (bestKey !== null) {
      // LRU touch: move to the tail of the insertion order.
      const entry = this.entries.get(bestKey);
      if (entry !== undefined) {
        this.entries.delete(bestKey);
        this.entries.set(bestKey, entry);
      }
    }
    return best;
  }

  /** Records (or refreshes) the fingerprint -> conversation mapping. */
  record(sequence: readonly OpenAIMessage[], conversationId: string): void {
    const filtered = sequence.filter((message) => message.role !== "system");
    if (filtered.length === 0 || conversationId === "") {
      return;
    }
    const hashes = prefixHashes(filtered);
    const fingerprint = hashes[filtered.length];
    if (fingerprint === undefined) {
      return;
    }
    const key = fingerprint.toString(36);
    this.entries.delete(key);
    this.entries.set(key, { fingerprint, count: filtered.length, conversationId });
    while (this.entries.size > this.capacity) {
      const oldest = this.entries.keys().next().value;
      if (oldest === undefined) {
        break;
      }
      this.entries.delete(oldest);
    }
  }
}